# Generated by Django 3.2.6 on 2021-08-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210817_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreaction',
            old_name='rare_user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateField(),
        ),
    ]
