# Generated by Django 3.2.6 on 2021-08-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20210817_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostReaction',
        ),
    ]
